export interface BlogPost {
  slug: string
  title: string
  excerpt: string
  date: string
  readingTime: string
  category: string
  image: string
  content: string[]   // array of paragraphs, rendered as <p> tags
}

export const blogPosts: BlogPost[] = [
  {
    slug: 'como-elegir-ventanas-aluminio-bilbao',
    title: 'Cómo elegir ventanas de aluminio para tu vivienda en Bilbao',
    excerpt: 'Descubre qué factores influyen en el aislamiento térmico y acústico, qué marcas son las más recomendadas en Vizcaya y cómo solicitar un presupuesto sin sorpresas.',
    date: '2026-01-15',
    readingTime: '6 min',
    category: 'Guía de compra',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
    content: [
      'Elegir las ventanas adecuadas para tu vivienda en Bilbao es una de las decisiones más importantes que afectarán al confort, al consumo energético y al valor de tu hogar durante décadas. No todas las ventanas son iguales, y la diferencia entre una instalación de calidad y una mediocre puede suponer miles de euros en calefacción, humedad y reparaciones a lo largo de los años.',
      'El clima atlántico del País Vasco impone condiciones exigentes a cualquier cerramiento exterior. Bilbao registra una pluviometría media de más de 1.200 mm al año, con frecuentes rachas de viento procedentes del mar Cantábrico y amplitudes térmicas moderadas pero constantes. Las ventanas de tu vivienda deben soportar presión de agua, viento y condensación de forma continuada sin deteriorarse ni permitir filtraciones.',
      'La solución técnica más recomendada para el clima de Bizkaia es el aluminio con rotura de puente térmico (RPT). Este sistema incorpora una barrera de material plástico en el interior del perfil metálico que interrumpe la conductividad del aluminio, evitando que el frío exterior se transmita al interior y reduciendo drásticamente la condensación en el marco. Sin RPT, el aluminio tradicional conduce el frío directamente hacia dentro, generando humedad en los bordes de las ventanas.',
      'A la hora de comparar ventanas, el indicador técnico más importante es el coeficiente Uw, que mide la transmitancia térmica del conjunto (perfil más vidrio). Un Uw bajo indica mayor aislamiento: en viviendas convencionales se recomienda un valor inferior a 1,4 W/m²K, mientras que para estándares Passivhaus se buscan valores por debajo de 0,8 W/m²K. El acristalamiento también es determinante: el doble vidrio con cámara de argón es el estándar actual, pero el triple acristalamiento ofrece un salto significativo para plantas bajas o fachadas orientadas al norte.',
      "En Comercial MAR'O trabajamos con la gama Ecoven Plus, que agrupa tres series diseñadas para distintos niveles de exigencia. La Serie S70 es ideal para reformas convencionales sin renunciar a un rendimiento térmico solvente. La Serie S76, la más elegida para obra nueva y rehabilitaciones energéticas, da un paso más en anchura de cámara y refuerzo estructural. La Serie S82 alcanza valores de aislamiento compatibles con la certificación Passivhaus, con perfiles de 82 mm y posibilidad de triple vidrio.",
      'Otro aspecto que merece atención es el tipo de apertura. La ventana oscilobatiente combina ventilación controlada (modo báscula) con apertura total (modo batiente) y ofrece excelente estanqueidad. Las ventanas correderas son perfectas para conexiones con terrazas o jardines, aunque su estanqueidad al aire es algo inferior. Las ventanas paralelas o Vekamotion permiten aberturas muy amplias con un mecanismo de elevación que garantiza estanqueidad comparable a la oscilobatiente incluso en grandes formatos.',
      'El acristalamiento es responsable de aproximadamente el 70 % de la transmitancia térmica total de la ventana. Para uso residencial en Bilbao recomendamos el vidrio doble con cámara de argón de al menos 16 mm y un factor solar bajo en fachadas sur para evitar el sobrecalentamiento en verano. En habitaciones orientadas al norte o en planta baja, un vidrio con tratamiento de baja emisividad (low-e) mejora sensiblemente la temperatura radiante percibida en invierno.',
      'El aislamiento acústico es otra variable que los propietarios bilbaínos suelen subestimar hasta que sufren el ruido del tráfico o de la lluvia. Los perfiles de aluminio con RPT ofrecen una atenuación acústica base de entre 30 y 35 dB, pero si tu vivienda está en una vía principal o cerca de una zona de ocio, es recomendable combinar el perfil con vidrio laminado acústico. La diferencia entre 42 dB y 32 dB en el dormitorio es enorme para la calidad del sueño.',
      'Los acabados del aluminio son otro punto diferencial. La gran mayoría de perfiles se suministran lacados en polvo bajo norma Qualicoat, con una paleta de cientos de colores RAL e imitación de madera disponibles en versión bicolor: un color por la cara exterior y otro por la interior. Esto permite combinar, por ejemplo, un gris antracita en fachada con blanco hueso interior. La durabilidad de la laca sobre aluminio supera habitualmente los 30 años sin necesidad de repintado.',
      "Trabajamos con sistemas de Cortizo, Reynaers y Technal, tres fabricantes europeos líderes con los que mantenemos acuerdos de instalador certificado. Esto garantiza el acceso a sistemas técnicamente homologados, vidrios y accesorios originales, y una garantía de fabricante sobre los perfiles. No todos los instaladores tienen acceso a las gamas premium de estos fabricantes ni a la formación técnica que exigen para su correcta instalación.",
      "En Comercial MAR'O realizamos visitas de medición gratuitas y sin compromiso en Bilbao y toda Vizcaya. Durante la visita analizamos la orientación de cada hueco, el uso previsto y el presupuesto disponible para ofrecerte la solución más adecuada. El presupuesto detallado, con especificaciones técnicas y referencias de cada producto, se entrega habitualmente en un plazo de 48 horas.",
    ],
  },
  {
    slug: 'pergolas-bioclimaticas-pais-vasco',
    title: 'Pérgolas bioclimáticas en el País Vasco: todo lo que necesitas saber',
    excerpt: 'Las pérgolas bioclimáticas son cada vez más populares en Euskadi. Te explicamos cómo funcionan y si son una buena inversión para el clima del norte de España.',
    date: '2026-02-08',
    readingTime: '5 min',
    category: 'Productos',
    image: 'https://images.unsplash.com/photo-1616137466211-f939a420be84?w=800',
    content: [
      'Una pérgola bioclimática es una estructura de cubierta motorizada formada por lamas de aluminio orientables que permiten regular la entrada de luz solar, la ventilación y la protección frente a la lluvia, todo ello con un solo mando o desde una aplicación móvil. A diferencia de una pérgola convencional con techo fijo, las lamas se ajustan en ángulo de 0° a 135°, creando condiciones de confort muy distintas según la hora del día o las condiciones meteorológicas.',
      'La demanda de pérgolas bioclimáticas en el País Vasco ha crecido de forma sostenida en los últimos años, y el motivo principal es paradójico: precisamente el clima atlántico que a priori parece desaconsejable para disfrutar de la terraza es el que más se beneficia de esta tecnología. Una terraza sin cubierta en Bilbao está inutilizable durante meses; con una pérgola bioclimática, ese mismo espacio se convierte en habitable prácticamente todo el año.',
      'El funcionamiento del sistema es sencillo pero efectivo. Cuando las lamas están en posición horizontal (0°), la pérgola actúa como un techo impermeable que evacúa el agua de lluvia a través de canales integrados en los pilares. Al inclinarlas a 45°, deja pasar luz filtrada y crea ventilación natural sin que entre el agua. A 90° o más, el espacio queda completamente abierto al cielo. Los sensores de lluvia y viento que incorporan los modelos más avanzados automatizan este ajuste sin intervención manual.',
      'La motorización es estándar en la práctica totalidad de las instalaciones actuales. La integración con sistemas domóticos como KNX, Somfy TaHoma o asistentes de voz permite controlar la pérgola desde cualquier dispositivo o incluirla en rutinas automatizadas, como cerrar las lamas al detectar lluvia o abrirlas una hora antes del atardecer. Esta conectividad es especialmente valorada en segundas residencias o locales comerciales donde la supervisión remota aporta tranquilidad.',
      'Las opciones de equipamiento son muy amplias. La iluminación LED perimetral en el interior del cajón o en los pilares convierte la terraza en un espacio nocturno atractivo sin cables a la vista. Los calefactores de infrarrojo instalados en el techo entre las lamas alargan el uso de la terraza hasta los meses más fríos. Los toldos laterales —cortinas de cristal, screens enrollables o telas técnicas— completan el cerramiento perimetral para crear un espacio totalmente protegido del viento y la lluvia lateral.',
      'Desde el punto de vista normativo, en Bilbao y en la mayoría de municipios de Bizkaia la instalación de una pérgola bioclimática sobre terraza privada no requiere licencia de obras si la estructura no supera los 30 m² y no modifica la volumetría del edificio. Es recomendable verificar las ordenanzas municipales y el reglamento de la comunidad de propietarios antes de proceder, ya que edificios con protección arquitectónica pueden tener restricciones adicionales.',
      'El mantenimiento de una pérgola bioclimática de aluminio lacado es mínimo. Una limpieza con agua y jabón neutro dos veces al año, junto con una revisión anual de los mecanismos de motorización y los canales de desagüe, es suficiente para garantizar un funcionamiento óptimo durante décadas. No requieren pintura ni tratamientos adicionales.',
      "En Comercial MAR'O el proceso comienza con una visita técnica gratuita para tomar medidas y valorar las condiciones de anclaje. Diseñamos el proyecto con las dimensiones exactas y el equipamiento seleccionado, y presentamos el presupuesto en 48 horas. El plazo de fabricación habitual es de 4 a 6 semanas desde la confirmación del pedido, y la instalación se realiza en uno o dos días según la complejidad del proyecto.",
      'Una pérgola bioclimática de calidad representa entre 4.000 y 15.000 euros según dimensiones y equipamiento, pero añade superficie habitable al hogar y aumenta el valor de la propiedad. Los estudios de tasación estiman que una terraza cubierta y equipada puede incrementar el valor de un piso en un 8-12 % respecto a una terraza sin cubrir, una rentabilidad que en el mercado inmobiliario bilbaíno actual hace de esta instalación una inversión muy razonable.',
    ],
  },
  {
    slug: 'aluminio-vs-pvc-diferencias',
    title: 'Diferencias entre carpintería de aluminio y PVC',
    excerpt: '¿Aluminio o PVC? Comparamos durabilidad, aislamiento, precio y mantenimiento para que tomes la mejor decisión para tu hogar en Vizcaya.',
    date: '2026-02-20',
    readingTime: '4 min',
    category: 'Comparativas',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    content: [
      'La elección entre carpintería de aluminio y PVC es, sin duda, la pregunta que más nos hacen nuestros clientes antes de iniciar una reforma en Bilbao. Ambos materiales han evolucionado enormemente en los últimos veinte años y los dos son opciones válidas en según qué contexto, pero conocer sus diferencias reales —más allá de los tópicos— te ayudará a tomar una decisión informada.',
      'En materia de aislamiento térmico, el debate entre aluminio con rotura de puente térmico (RPT) y PVC está hoy prácticamente resuelto en empate técnico para soluciones domésticas estándar. Un perfil de aluminio RPT bien configurado alcanza los mismos valores de transmitancia que un perfil de PVC de 5 o 6 cámaras. La diferencia real aparece en los extremos: el aluminio puede alcanzar certificaciones Passivhaus con series de 82 mm, algo que el PVC solo consigue con perfiles muy anchos y pesados. Para el 90 % de las viviendas convencionales en Bizkaia, el aislamiento de ambos materiales es comparable con una instalación bien ejecutada.',
      'El aislamiento acústico es ligeramente superior en el PVC, ya que la masa del material amortigua mejor las vibraciones de baja frecuencia. Sin embargo, esta ventaja se neutraliza casi por completo cuando se combina el aluminio RPT con vidrio laminado acústico, que es la solución estándar en viviendas situadas cerca de vías de tráfico intenso. En ambos casos, el acristalamiento es el factor que más influye en el resultado acústico final.',
      'Donde el aluminio gana de forma clara es en durabilidad y resistencia mecánica. Los perfiles de aluminio lacado bajo norma Qualicoat mantienen sus propiedades durante más de 40 años sin deformaciones, incluso en climas salinos o expuestos al sol intenso. El PVC puede amarillear con el tiempo en fachadas muy soleadas y tiende a ablandarse ligeramente con el calor, lo que en formatos grandes puede provocar problemas de alineación. En el contexto húmedo de Bilbao el PVC se comporta bien, pero en fachadas sur o en segunda residencia en la costa, el aluminio ofrece mayor garantía a largo plazo.',
      'La versatilidad estética del aluminio es otra ventaja significativa. Los perfiles se suministran en cualquier color RAL, con acabados mate, satinado o brillante, imitaciones de madera, y en versión bicolor (distinto color interior y exterior). Esto permite adaptar la carpintería al estilo arquitectónico del edificio con un grado de libertad muy superior al PVC. Para edificios con fachada de diseño, rehabilitaciones en zonas históricas de Bilbao o proyectos donde la estética es determinante, el aluminio es la elección natural.',
      'En cuanto al precio, el PVC presenta habitualmente un coste de fabricación e instalación entre un 15 y un 25 % inferior al aluminio con RPT en la misma configuración. Esta diferencia se reduce cuando el aluminio elegido es de gama media-alta y el PVC de gama premium. En cualquier caso, el menor precio inicial del PVC puede compensarse a largo plazo con el mayor valor residual que aporta el aluminio en una vivienda, especialmente relevante si existe posibilidad de venta futura.',
      'Desde el punto de vista medioambiental, el aluminio es el material más reciclable de los dos: puede reciclarse indefinidamente sin pérdida de propiedades, y la industria europea recupera actualmente más del 95 % del aluminio de construcción al final de su vida útil. El PVC también es reciclable, aunque la cadena logística de reciclaje es menos desarrollada y el material reciclado tiene un rango de aplicaciones más limitado.',
      "En Comercial MAR'O trabajamos principalmente con aluminio con rotura de puente térmico porque es el material que mejor se adapta a las exigencias técnicas y estéticas de los proyectos en el norte de España. Si tu presupuesto es limitado o las condiciones del proyecto hacen del PVC la opción más adecuada, también ofrecemos soluciones en este material con los mismos estándares de instalación. Lo importante no es el material, sino que el resultado sea el que mejor se adapta a tus necesidades.",
    ],
  },
  {
    slug: 'precio-ventanas-aluminio-vizcaya',
    title: 'Cuánto cuesta instalar ventanas de aluminio en Vizcaya',
    excerpt: 'Precios orientativos para la instalación de ventanas de aluminio en Bilbao y Vizcaya en 2026. Factores que afectan al coste y cómo obtener el mejor presupuesto.',
    date: '2026-03-05',
    readingTime: '5 min',
    category: 'Precios',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
    content: [
      'El precio de instalar ventanas de aluminio en Vizcaya depende de tantas variables que cualquier cifra dada sin conocer el proyecto concreto es orientativa en el mejor de los casos. Dicho esto, disponer de una horquilla de referencia te ayudará a identificar presupuestos fuera de mercado —tanto los excesivamente baratos como los injustificadamente caros— y a prepararte para una conversación más informada con tu instalador.',
      'Los factores que más influyen en el precio son, por orden de impacto: el tipo y serie de perfil elegido (S70, S76, S82 u otras gamas), las dimensiones y número de hojas de cada ventana, el tipo de vidrio (doble estándar, doble bajo emisivo, triple), el acabado (color estándar blanco o colores especiales), el tipo de apertura (oscilobatiente, corredera, paralela), y la accesibilidad del edificio para la instalación.',
      'Como referencia orientativa para Bilbao en 2026, una ventana oscilobatiente estándar de 120×120 cm en serie S70 con doble vidrio argón y color blanco se sitúa habitualmente entre 380 y 480 euros instalada. La misma ventana en serie S76 con vidrio bajo emisivo cuesta entre 480 y 620 euros, y en serie S82 con triple vidrio, entre 650 y 900 euros. Estas cifras incluyen fabricación, transporte, instalación y remates. No incluyen, salvo que se especifique, la retirada de la carpintería antigua.',
      'Las ventanas correderas de gran formato —muy demandadas para comunicar salones con terrazas— tienen un coste notablemente superior. Una corredera de dos hojas de 200×210 cm en aluminio RPT serie S76 puede oscilar entre 1.200 y 2.000 euros instalada, dependiendo del peso del vidrio y del sistema de rodadura. Las paralelas-plegables de formato similar, con su mecanismo de elevación y mayor estanqueidad, se sitúan entre 1.800 y 3.000 euros para la misma apertura.',
      'Para hacerse una idea del presupuesto total de una reforma integral, una vivienda de 90 m² en Bilbao con 8-10 huecos de carpintería suele tener un coste de entre 8.000 y 18.000 euros dependiendo de la gama elegida y la complejidad de los huecos. Las reformas de edificios de viviendas plurifamiliares permiten reducir el coste unitario gracias a la economía de escala, y en muchos casos pueden acogerse a los programas de ayudas del Gobierno Vasco para rehabilitación energética.',
      'Un presupuesto muy bajo —ventanas oscilobatientes de 120×120 cm por menos de 250 euros instaladas— debería hacer saltar las alarmas. Los perfiles de bajo coste suelen carecer de rotura de puente térmico efectiva y el vidrio utilizado es a menudo doble acristalamiento simple sin cámara de argón ni tratamiento low-e. El ahorro inicial puede convertirse en facturas de calefacción elevadas, condensaciones y problemas de estanqueidad en los primeros años.',
      'Un presupuesto riguroso debe incluir: medición in situ de cada hueco, especificación técnica completa del perfil (serie, fabricante, certificaciones), referencia exacta del vidrio con su Ug y Uw, acabado y color con muestra de referencia, plazo de fabricación e instalación, condiciones de garantía del producto y de la mano de obra, y servicio posventa. Cualquier presupuesto que no incluya estos datos por escrito no permite una comparación real entre distintos instaladores.',
      'En Vizcaya existen varias líneas de ayudas públicas para la mejora de la envolvente térmica de los edificios. El Programa de Ayudas para la Rehabilitación Energética de Edificios (PREE) y las convocatorias del Departamento de Medio Ambiente del Gobierno Vasco cofinancian hasta el 40 % del coste de sustitución de ventanas en edificios residenciales que alcancen una mejora mínima en la calificación energética.',
      'La inversión en ventanas de calidad tiene un retorno medible. Estudios del IDAE estiman que la sustitución de carpintería antigua por aluminio RPT con doble acristalamiento bajo emisivo puede reducir las pérdidas de calor a través de la envolvente en un 30-40 %, lo que se traduce en un ahorro medio de entre 300 y 600 euros anuales en calefacción para un piso tipo en Bilbao. A ese ritmo, la inversión adicional respecto a una solución económica se amortiza en 5-8 años.',
    ],
  },
]
